[versions]
kspVersion = "1.9.54"
minSdk = "21"
compileSdk = "34"
targetSdk = "34"


kotlin = "1.9.10"
gradlePluginVersion = "8.1.0"


ksp = "1.9.10-1.0.13"
material = "1.11.0"

lifecycleRuntimeKtx = "2.6.2"
activityCompose = "1.8.2"

compose = "1.5.4"
composeMaterial = "1.5.4"
composeCompiler = "1.5.3"
composeNavigation = "2.7.6"
composeViewModel = "2.6.2"
composePreview = "1.5.4"
[libraries]

# Plugins
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "kspVersion" }
pluginVersion = { module = "com.android.tools.build:gradle", version.ref = "gradlePluginVersion" }

# Android
androidMaterial = { module = "com.google.android.material:material", version.ref = "material" }

# AndroidX
androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composePreview" }